name: Docker Build and Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build Docker image and Scan with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t repo1-image .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: repo1-image
          format: table
          exit-code: 1
          severity: CRITICAL

  notify:
    name: Teams Notification (State Aware)
    needs: build-and-scan
    if: always()
    uses: RAVIKUMAR-DEKKA/Repo-1/.github/workflows/teams-notify-stateful.yml@main
    with:
      status: ${{ needs.build-and-scan.result }}
      repo: ${{ github.repository }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
    secrets:
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
